In [1]:
import torch
import numpy as np

# torch基础
1. 通过多种方法生成Tensor
3. tensor相关数据查看
3. tensor和numpy之间转化
4. GPU的相关内容
5. 梯度部分

In [2]:
# 通过多种方法生成Tensor
x1 = torch.empty(4, 6, dtype=torch.float16)     # 未被初始化
x2 = torch.randn((3, 5), requires_grad=True)                          # 正太分布，均值0，方差1
x3 = torch.rand(3, 5)                           # 0~1之间
x4 = torch.zeros(3, 5).float()                  # 全0
x5 = torch.ones(3, 5).float()                   # 全1

x6 = torch.tensor([[1, 2],[3, 4]])              # 自定义
x7 = x4.new_ones(3, 5, dtype=torch.double)      # 通过其他数据集构建
x8 = torch.rand_like(x5, dtype=torch.float)

In [3]:
y1 = x1.view(2, -1)
y1
print('y1 contains function:', dir(y1))

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=torch.float16)

y1 contains function: ['T', '__abs__', '__add__', '__and__', '__array__', '__array_priority__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__div__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__idiv__', '__ifloordiv__', '__ilshift__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__long__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdiv__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rfloordiv__', '__rlshift__', '__rmatmul__', '__

In [4]:
x1, x2, x3, x4, x5, x6, x7, x8,

(tensor([[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]], dtype=torch.float16),
 tensor([[ 0.7561,  0.1417, -0.2391, -0.2577,  1.0459],
         [-0.9544, -0.9509, -0.4781,  0.0031, -1.8838],
         [-0.3575, -0.1970,  0.2644, -0.3667, -0.0513]], requires_grad=True),
 tensor([[0.1031, 0.9093, 0.5653, 0.3168, 0.8105],
         [0.6227, 0.9637, 0.2834, 0.9208, 0.7526],
         [0.2035, 0.8109, 0.3670, 0.3252, 0.9486]]),
 tensor([[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]),
 tensor([[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]),
 tensor([[1, 2],
         [3, 4]]),
 tensor([[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]], dtype=torch.float64),
 tensor([[0.1456, 0.5287, 0.6870, 0.0680, 0.1655],
         [0.8290, 0.4854, 0.9880, 0.5742, 0.7527],
         [0.1087, 0.4370, 0.3434, 0.9482, 0.9027

In [5]:
# tensor相关数据查看
# transform tensor to data
x2.data
x2.grad_fn
x2[1][1].item()  # 将其中一个张量转化为标量
x2.size()
x2.shape
x2.numel()  # 张量中元素的总数
# dir(x2)

tensor([[ 0.7561,  0.1417, -0.2391, -0.2577,  1.0459],
        [-0.9544, -0.9509, -0.4781,  0.0031, -1.8838],
        [-0.3575, -0.1970,  0.2644, -0.3667, -0.0513]])

-0.950921893119812

torch.Size([3, 5])

torch.Size([3, 5])

15

In [6]:
# tensor和numpy之间转化
# conversion between numpy with tensor
print('x3 to numpy:\n', x3.numpy())
y2 = np.ones((2, 3))
print('y2:\n', y2)
print('y2 to tensor:\n', torch.from_numpy(y2))

x3 to numpy:
 [[0.10310835 0.90929145 0.56531936 0.31677252 0.8105179 ]
 [0.6227076  0.96370554 0.2833556  0.9207854  0.7525864 ]
 [0.20351934 0.8108965  0.36703002 0.3252105  0.94863856]]
y2:
 [[1. 1. 1.]
 [1. 1. 1.]]
y2 to tensor:
 tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [7]:
# GPU的相关内容
if torch.cuda.is_available():
    device = torch.device('cuda')
    y3 = torch.randn((2, 3), device=device)
    xy3 = y3.to(device)
    
    print('xy3 in gpu is:', xy3)
    print('xy3 in cpu is:', xy3.to('cpu', torch.double))
    # GPU的tensor转numpy。需要通过cpu做桥梁
    print('xy3 in numpu is:', xy3.cpu().data.numpy())
else:
    print('device is cpu')

x6.cuda(device)
x6.cuda(0)
x6.device
y3.device
x6.to(y3.device)

torch.cuda.device_count()               # 设备的GPU数量
torch.cuda.get_device_name(0)           # 查看GPU的型号
torch.cuda.current_device()             # 当前设备索引
torch.cuda.get_device_capability(0)     # 当前设备计算能力
torch.cuda.get_device_properties(0)     # 当前设备综合性能

xy3 in gpu is: tensor([[-0.1392, -0.1516,  0.0575],
        [ 1.7836, -0.0648, -2.6153]], device='cuda:0')
xy3 in cpu is: tensor([[-0.1392, -0.1516,  0.0575],
        [ 1.7836, -0.0648, -2.6153]], dtype=torch.float64)
xy3 in numpu is: [[-0.13917635 -0.15162571  0.05748875]
 [ 1.7836003  -0.06475431 -2.615291  ]]


tensor([[1, 2],
        [3, 4]], device='cuda:0')

tensor([[1, 2],
        [3, 4]], device='cuda:0')

device(type='cpu')

device(type='cuda', index=0)

tensor([[1, 2],
        [3, 4]], device='cuda:0')

1

'TITAN Xp'

0

(6, 1)

_CudaDeviceProperties(name='TITAN Xp', major=6, minor=1, total_memory=12288MB, multi_processor_count=30)

In [8]:
## 梯度部分
import torch
# 随机出张量x 指定可以计算偏导数
x = torch.randn(1,requires_grad=True)
# y和z张量不可以求偏导
y = torch.randn(1)
z = torch.randn(1)
# f1中有张量允许求偏导
f1 = 2*x + y
# f2中没有张量可以允许求偏导
f2 = y + z
# 打印两个方程的梯度
print(f1.grad_fn)
print(f2.grad_fn)

# 可以求梯度的变量先使用backward()反向传播
f1.backward()
# f2.backward()
# 使用张量的grad属性拿到偏导数的值
x.grad
# z.grad


None


tensor([2.])